baseURL = "https://msrsaditya.github.io/"
languageCode = "en-us"
title = "Shashank's Blog"
theme = "PaperMod"
[assets]
  disableHLJS = false
[params]
  author = "Shashank Aditya"
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  [params.profileMode]
    enabled = false
  [params.footer]
    hideCopyright = true
    hidePoweredBy = true
  [[params.socialIcons]]
    name = "Email"
    url = "mailto:msrsaditya@gmail.com"
  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/msrsaditya"
  [[params.socialIcons]]
    name = "X"
    url = "https://x.com/msrsaditya"
  [[params.socialIcons]]
    name = "Website"
    url = "https://msrsaditya.github.io/About"
